### ISSUE TITLE
How would we adjust the code to calculate implied volatility for a call option? 

### ISSUE THREAD

**Issue by tradegreek** [PacktPublishing/Mastering-Python-for-Finance-Second-Edition#2]
I was hoping it would be as simple as changing the is_put = False but it kicks up this error? 

Traceback (most recent call last):
  File "implied_volatility.py", line 44, in <module>
    impvols_put = model.get_implied_volatilities(strikes, put_prices)
  File "implied_volatility.py", line 33, in get_implied_volatilities
    impv = bisection(f, 0.01, 0.99, 0.0001, 100)[0]
  File "C:\Python38\Lib\site-packages\bisection.py", line 15, in bisection
    if f(c) == 0 or abs(a-b)*0.5 < tol:
  File "implied_volatility.py", line 31, in <lambda>
    self.option_valuation(Ks[i], sigma)-\
  File "implied_volatility.py", line 24, in option_valuation
    return lr_option.price()
  File "C:\Python38\Lib\site-packages\BinomialTreeOption.py", line 59, in price
    self.setup_parameters()
  File "C:\Python38\Lib\site-packages\BinomialLROption.py", line 23, in setup_parameters
    self.d = (1/self.df-self.p*self.u)/(1-self.p)
ZeroDivisionError: float division by zero

the self.d = (1/self.df-self.p*self.u)/(1-self.p) comes from the BinomialLROption script
I tried to fix the problem by increasing N but I think the results are inccorect 

I think its just a mathmatical issue caused by numbers being near 0 when you use a more realistic scenario i.e not just flip to false it seems to produce accurate numbers.

**Comment by tradegreek** [comment]
Changed N to 5000 and is_put = False and I get 

[0.010000000912696122, 0.010000000912696122, 0.010000000912696122, 0.010000000912696122, 0.010000000912696122, 0.010000000912696122, 0.12356320904567837, 0.26770574586465956, 0.5402337853796781, 0.8561477058194575, 0.9899999990873039, 0.9899999990873039, 0.9899999990873039] 

for 125 strike and a call of 25.81 the IV should be around 180% according to online IV calculators.
